sqlite_defaults: &sqlite_defaults
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

postgres_defaults: &postgres_defaults
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *sqlite_defaults
  database: db/development.sqlite3

production:
  <<: *postgres_defaults
  url: <%= ENV['DATABASE_URL'] %>

cable:
  <<: *postgres_defaults
  url: <%= ENV['CABLE_DATABASE_URL'] || ENV['DATABASE_URL'] %>

queue:
  <<: *postgres_defaults
  url: <%= ENV['DATABASE_URL'] %>
