default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: padel_development

test:
  <<: *default
  database: padel_test

production:
  adapter: postgresql
  encoding: unicode
  database: de0bqup6hn6ns
  username: u920s7epto2rvr
  password: pc7a31a81f8c184b5b5ae2fb3aa28083e94e555a6aa348647bfb25629a75ac2ff
  host: c7s7ncbk19n97r.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com
  port: 5432
  pool: 5

cable:
  <<: *default
  url: <%= ENV['CABLE_DATABASE_URL'] || ENV['DATABASE_URL'] %>
