sqlite_defaults: &sqlite_defaults
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

postgres_defaults: &postgres_defaults
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *sqlite_defaults
  database: db/development.sqlite3  # Cambio storage/ por db/, que es más estándar en Rails

test:
  <<: *sqlite_defaults
  database: db/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: 5432
  pool: 5
